// Code generated by proto-gen-vine. DO NOT EDIT.
// source: github.com/vine-io/examples/api/proto/hello.proto

package hello

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	client "github.com/vine-io/vine/core/client"
	registry "github.com/vine-io/vine/core/registry"
	server "github.com/vine-io/vine/core/server"
	api "github.com/vine-io/vine/lib/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// API Endpoints for Hello service
func NewHelloEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:        "Hello.Echo",
			Description: "Hello.Echo",
			Path:        []string{"/api/v1/echo/{name}"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
	}
}

// Swagger OpenAPI 3.0 for Hello service
func NewHelloOpenAPI() *registry.OpenAPI {
	return &registry.OpenAPI{
		Openapi: "3.0.1",
		Info: &registry.OpenAPIInfo{
			Title:       "HelloService",
			Description: "OpenAPI3.0 for Hello",
			Version:     "v1.0.0",
		},
		Servers: []*registry.OpenAPIServer{},
		Tags: []*registry.OpenAPITag{
			&registry.OpenAPITag{
				Name:        "Hello",
				Description: "OpenAPI3.0 for Hello",
			},
		},
		Paths: map[string]*registry.OpenAPIPath{
			"/api/v1/echo/{name}": &registry.OpenAPIPath{
				Get: &registry.OpenAPIPathDocs{
					Tags:        []string{"Hello"},
					Description: "Hello Echo",
					OperationId: "HelloEcho",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "EchoReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/proto.EchoRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
		},
		Components: &registry.OpenAPIComponents{
			SecuritySchemes: &registry.SecuritySchemes{},
			Schemas: map[string]*registry.Model{
				"proto.EchoReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
				},
				"proto.EchoRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"reply": &registry.Schema{
							Type: "string",
						},
					},
				},
			},
		},
	}
}

// Client API for Hello service
// +gen:openapi
type HelloService interface {
	// +gen:get=/api/v1/echo/{name}
	Echo(ctx context.Context, in *EchoReq, opts ...client.CallOption) (*EchoRsp, error)
}

type helloService struct {
	c    client.Client
	name string
}

func NewHelloService(name string, c client.Client) HelloService {
	return &helloService{
		c:    c,
		name: name,
	}
}

func (c *helloService) Echo(ctx context.Context, in *EchoReq, opts ...client.CallOption) (*EchoRsp, error) {
	req := c.c.NewRequest(c.name, "Hello.Echo", in)
	out := new(EchoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service
// +gen:openapi
type HelloHandler interface {
	// +gen:get=/api/v1/echo/{name}
	Echo(context.Context, *EchoReq, *EchoRsp) error
}

func RegisterHelloHandler(s server.Server, hdlr HelloHandler, opts ...server.HandlerOption) error {
	type helloImpl interface {
		Echo(ctx context.Context, in *EchoReq, out *EchoRsp) error
	}
	type Hello struct {
		helloImpl
	}
	h := &helloHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "Hello.Echo",
		Description: "Hello.Echo",
		Path:        []string{"/api/v1/echo/{name}"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, server.OpenAPIHandler(NewHelloOpenAPI()))
	return s.Handle(s.NewHandler(&Hello{h}, opts...))
}

type helloHandler struct {
	HelloHandler
}

func (h *helloHandler) Echo(ctx context.Context, in *EchoReq, out *EchoRsp) error {
	return h.HelloHandler.Echo(ctx, in, out)
}
