// Code generated by proto-gen-validator. DO NOT EDIT.
// source: pb/hello.proto

package hello

import (
	fmt "fmt"
	is "github.com/vine-io/vine/util/is"
)

func (m *Request) Validate() error {
	return m.ValidateE("")
}

func (m *Request) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Name) == 0 {
		errs = append(errs, fmt.Errorf("field '%sname' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *Response) Validate() error {
	return m.ValidateE("")
}

func (m *Response) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}
